/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ApiDoc {
    'src': string;
  }
  interface ApiDocAttributes extends StencilHTMLAttributes {
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ApiDoc': Components.ApiDoc;
  }

  interface StencilIntrinsicElements {
    'api-doc': Components.ApiDocAttributes;
  }


  interface HTMLApiDocElement extends Components.ApiDoc, HTMLStencilElement {}
  var HTMLApiDocElement: {
    prototype: HTMLApiDocElement;
    new (): HTMLApiDocElement;
  };

  interface HTMLElementTagNameMap {
    'api-doc': HTMLApiDocElement
  }

  interface ElementTagNameMap {
    'api-doc': HTMLApiDocElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
